AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Eyes Slack Bot
Resources:
  SlackBot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        Eyes:
          Type: Api
          Properties:
            Path: /eyes
            Method: post
            VpcConfig:
              SecurityGroupIds:
                - !Ref GameStoreSg
              SubnetIds:
                - !Ref Subnet

  GameStore:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: cache.t2.micro
      NumCacheNodes: 1
      CacheSubnetGroupName: !Ref Subnet
      VpcSecurityGroupIds: 
  
  GameStoreSG:
    Type: AWS::EC2:SecurityGroup
    Properties:
      GroupDescription: Security Group for the redis instance
      SecurityGroupIngress:
        -
          CidrIp: !GetAtt Vpc.CidrBlock
          FromPort: !GetAtt GameStore.RedisEndpoint.Port
          ToPort: !GetAtt GameStore.RedisEndpoint.Port
          IpProtocol: tcp
      VpcId: !Ref VPC

  Subnet:
    Type: AWS::EC2::Subnet
    CidrBlock: !GetAtt VPC.CidrBlock
    VpcId: !Ref VPC

  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/24
  
  
  
    

